import React, { useState } from 'react';
import styles from './styles.module.css';

/* =====================================================================
   Shared pieces
   ===================================================================== */

// Box with vertically centered lines of text.
// lines: [{ t: 'text', c: 'title' | 'titleSm' | 'sub' | 'hubTitle' | 'hubSub' }]
function Box({ x, y, w, h, kind = 'node', lines = [], rx = 8, lh = 17 }) {
  const cx = x + w / 2;
  const cy = y + h / 2;
  const startY = cy - ((lines.length - 1) * lh) / 2 + 4.5;
  return (
    <g>
      <rect x={x} y={y} width={w} height={h} rx={rx} className={styles[kind]} />
      <text textAnchor="middle">
        {lines.map((l, i) => (
          <tspan key={i} x={cx} y={startY + i * lh} className={styles[l.c || 'title']}>
            {l.t}
          </tspan>
        ))}
      </text>
    </g>
  );
}

function ArrowMarker({ id, kind = 'arrow' }) {
  return (
    <marker
      id={id}
      viewBox="0 0 10 10"
      refX="9"
      refY="5"
      markerWidth="7"
      markerHeight="7"
      orient="auto-start-reverse">
      <path d="M0,0 L10,5 L0,10 z" className={styles[kind]} />
    </marker>
  );
}

function Figure({ titleId, title, desc, viewBox, caption, minWidth, children }) {
  return (
    <figure className={styles.figure}>
      <div className={styles.scroll}>
        <svg
          className={styles.svg}
          style={minWidth ? { minWidth } : undefined}
          viewBox={viewBox}
          role="img"
          aria-labelledby={`${titleId}-t ${titleId}-d`}>
          <title id={`${titleId}-t`}>{title}</title>
          <desc id={`${titleId}-d`}>{desc}</desc>
          {children}
        </svg>
      </div>
      {caption && <figcaption className={styles.caption}>{caption}</figcaption>}
    </figure>
  );
}

function Legend({ x, y, items }) {
  let cx = x;
  return (
    <g>
      {items.map((it) => {
        const gx = cx;
        cx += 26 + it.t.length * 6.4 + 22;
        return (
          <g key={it.t}>
            <rect x={gx} y={y - 10} width={16} height={12} rx={3} className={styles[it.k]} />
            <text x={gx + 22} y={y} className={styles.legendText}>
              {it.t}
            </text>
          </g>
        );
      })}
    </g>
  );
}

/* =====================================================================
   1. The typical way vs. automated release notes
   ===================================================================== */

export function TypicalVsAutomated() {
  const top = [
    { t: 'Chase changes', s: 'across tickets + chat' },
    { t: 'Draft from scratch', s: 'in a doc or wiki' },
    { t: 'Email for review', s: 'PMs and engineers' },
    { t: 'Merge feedback', s: 'from many threads' },
    { t: 'Reformat + paste', s: 'into the web platform' },
    { t: 'Fix after publish', s: 'by hand, page by page' },
  ];
  const bottom = [
    { t: 'Write at the source', s: '4 fields on the work item', k: 'human' },
    { t: 'Generate', s: 'compare two releases', k: 'auto' },
    { t: 'Edit once', s: 'Markdown in Git', k: 'human' },
    { t: 'Review once', s: 'pull request, 24 hours', k: 'human' },
    { t: 'Publish by script', s: 'straight to the portal', k: 'auto' },
  ];

  const tW = 140;
  const tX = (i) => 10 + i * 168;
  const tY = 38;
  const bW = 164;
  const bX = (i) => 10 + i * 204;
  const bY = 216;
  const h = 64;

  return (
    <Figure
      titleId="rn-compare"
      title="The typical release notes process compared with automated release notes"
      desc="The typical way has six manual steps: chase changes across tickets and chat, draft from scratch in a doc, email the draft to PMs and engineers, merge feedback from many threads, reformat and paste into the web platform, and fix mistakes by hand after publishing. Two rework loops send the writer back: another review round after merging feedback, and a re-paste after every fix. Automated release notes have five steps in one pass with no loops: engineers and PMs write the note at the source in four work item fields, the notes are generated by comparing two releases, the writer edits once in Markdown in Git, PMs review once in a pull request within 24 hours, and a script publishes straight to the customer portal."
      viewBox="0 0 1000 332"
      minWidth={780}
      caption="Same goal, different shape. The typical process loops back on the writer; the automated one runs in a single pass from the work item to the customer.">
      <defs>
        <ArrowMarker id="rn-c-arrow" />
        <ArrowMarker id="rn-c-arrow-key" kind="arrowKey" />
        <ArrowMarker id="rn-c-arrow-bad" kind="arrowBad" />
      </defs>

      {/* ---------- Typical ---------- */}
      <text x={10} y={22} className={styles.heading}>
        The typical way
      </text>
      <text x={990} y={22} textAnchor="end" className={styles.statBad}>
        6 manual steps · 2 rework loops · the writer is the bottleneck
      </text>

      {top.slice(0, -1).map((_, i) => (
        <path
          key={`te${i}`}
          d={`M${tX(i) + tW} ${tY + h / 2} L${tX(i + 1) - 2} ${tY + h / 2}`}
          className={styles.edge}
          markerEnd="url(#rn-c-arrow)"
        />
      ))}

      <path
        d={`M${tX(3) + tW / 2} ${tY + h} C${tX(3) + tW / 2} 150 ${tX(1) + tW / 2} 150 ${tX(1) + tW / 2} ${tY + h + 2}`}
        className={styles.edgeBad}
        markerEnd="url(#rn-c-arrow-bad)"
      />
      <text x={(tX(3) + tX(1)) / 2 + tW / 2} y={156} textAnchor="middle" className={styles.edgeLabelBad}>
        another review round
      </text>

      <path
        d={`M${tX(5) + tW / 2} ${tY + h} C${tX(5) + tW / 2} 150 ${tX(4) + tW / 2} 150 ${tX(4) + tW / 2} ${tY + h + 2}`}
        className={styles.edgeBad}
        markerEnd="url(#rn-c-arrow-bad)"
      />
      <text x={(tX(5) + tX(4)) / 2 + tW / 2} y={156} textAnchor="middle" className={styles.edgeLabelBad}>
        every fix: re-paste
      </text>

      {top.map((b, i) => (
        <Box
          key={b.t}
          x={tX(i)}
          y={tY}
          w={tW}
          h={h}
          kind="manual"
          lines={[
            { t: b.t, c: 'titleSm' },
            { t: b.s, c: 'sub' },
          ]}
        />
      ))}

      <line x1={10} y1={178} x2={990} y2={178} className={styles.edge} strokeDasharray="2 5" />

      {/* ---------- Automated ---------- */}
      <text x={10} y={200} className={styles.heading}>
        Automated release notes
      </text>
      <text x={990} y={200} textAnchor="end" className={styles.statGood}>
        5 steps · 0 rework loops · every note traceable to its work item
      </text>

      {bottom.slice(0, -1).map((_, i) => (
        <path
          key={`be${i}`}
          d={`M${bX(i) + bW} ${bY + h / 2} L${bX(i + 1) - 2} ${bY + h / 2}`}
          className={styles.edgeKey}
          markerEnd="url(#rn-c-arrow-key)"
        />
      ))}

      {bottom.map((b, i) => (
        <g key={b.t}>
          <Box
            x={bX(i)}
            y={bY}
            w={bW}
            h={h}
            kind={b.k}
            lines={[
              { t: b.t, c: 'titleSm' },
              { t: b.s, c: 'sub' },
            ]}
          />
          <circle cx={bX(i) + 2} cy={bY + 2} r={10} className={styles.stepDot} />
          <text x={bX(i) + 2} y={bY + 6} textAnchor="middle" className={styles.stepNum}>
            {i + 1}
          </text>
        </g>
      ))}

      <Legend
        x={10}
        y={318}
        items={[
          { k: 'manual', t: 'manual handoff' },
          { k: 'human', t: 'human judgment, done once' },
          { k: 'auto', t: 'automated' },
        ]}
      />
    </Figure>
  );
}

/* =====================================================================
   2. The whole pipeline
   ===================================================================== */

export function PipelineMap() {
  const lane1 = [
    { t: 'Compare releases', a: 'filter by rules', b: 'sort by product', k: 'auto' },
    { t: 'Edit in Markdown', a: 'scripts clean the export', b: 'writer edits once', k: 'human' },
    { t: 'Pull request', a: 'PMs review in 24 hours', b: 'line-level comments', k: 'human' },
    { t: 'Publish scripts', a: 'assemble · style', b: 'post via REST API', k: 'auto' },
  ];
  const lane2 = [
    { t: 'Scheduled build', a: 'triggered daily', b: 'one per version', k: 'auto' },
    { t: 'Query + template', a: 'same fields', b: 'same rules', k: 'auto' },
    { t: 'Transform + publish', a: 'Markdown → styled HTML', b: 'post via REST API', k: 'auto' },
  ];

  const l1W = 140;
  const l1X = (i) => 200 + i * 160;
  const l1Y = 80;
  const l2W = 190;
  const l2X = (i) => 200 + i * 210;
  const l2Y = 245;
  const bh = 70;
  const l1C = l1Y + bh / 2;
  const l2C = l2Y + bh / 2;

  return (
    <Figure
      titleId="rn-map"
      title="How one set of work item fields feeds every release publication"
      desc="On the left, a work item with a release notes tab holding four fields: Publish, Release Note, Product(s) affected, and Version(s) affected, plus the work item's type, state, and severity. Two paths lead to the customer portal on the right. Every release: an extension compares two releases, filters work items by publishing rules, and sorts them by product; scripts clean the export into Markdown and the writer edits once; PMs review in a pull request within 24 hours; publish scripts assemble, style, and post the page through the portal's REST API. Every day, hands-off: a scheduled build for each version runs a query and template using the same fields and rules, transforms the Markdown to styled HTML, and posts known issues and critical and high bug reports through the REST API."
      viewBox="0 0 1000 380"
      minWidth={800}
      caption="Engineers and PMs fill in four fields once. Everything downstream is generated, and people step in only where judgment adds value.">
      <defs>
        <ArrowMarker id="rn-m-arrow" />
        <ArrowMarker id="rn-m-arrow-key" kind="arrowKey" />
      </defs>

      <rect x={192} y={30} width={660} height={150} rx={8} className={styles.lane} />
      <rect x={192} y={200} width={660} height={140} rx={8} className={styles.laneAlt} />
      <text x={204} y={52} className={styles.heading}>
        Every release · release notes
      </text>
      <text x={204} y={222} className={styles.heading}>
        Every day, hands-off · known issues + critical/high bugs
      </text>

      {/* Hub -> lanes */}
      <path
        d={`M175 150 C188 150 186 ${l1C} ${l1X(0) - 2} ${l1C}`}
        className={styles.edgeKey}
        markerEnd="url(#rn-m-arrow-key)"
      />
      <path
        d={`M175 220 C188 220 186 ${l2C} ${l2X(0) - 2} ${l2C}`}
        className={styles.edgeKey}
        markerEnd="url(#rn-m-arrow-key)"
      />

      {lane1.slice(0, -1).map((_, i) => (
        <path
          key={`l1e${i}`}
          d={`M${l1X(i) + l1W} ${l1C} L${l1X(i + 1) - 2} ${l1C}`}
          className={styles.edge}
          markerEnd="url(#rn-m-arrow)"
        />
      ))}
      {lane2.slice(0, -1).map((_, i) => (
        <path
          key={`l2e${i}`}
          d={`M${l2X(i) + l2W} ${l2C} L${l2X(i + 1) - 2} ${l2C}`}
          className={styles.edge}
          markerEnd="url(#rn-m-arrow)"
        />
      ))}

      {/* Lanes -> portal */}
      <path
        d={`M${l1X(3) + l1W} ${l1C} C${l1X(3) + l1W + 30} ${l1C} 840 150 863 150`}
        className={styles.edgeKey}
        markerEnd="url(#rn-m-arrow-key)"
      />
      <path
        d={`M${l2X(2) + l2W} ${l2C} C${l2X(2) + l2W + 30} ${l2C} 840 220 863 220`}
        className={styles.edgeKey}
        markerEnd="url(#rn-m-arrow-key)"
      />

      <Box
        x={10}
        y={80}
        w={165}
        h={210}
        kind="hub"
        lh={21}
        lines={[
          { t: 'Work item', c: 'hubTitle' },
          { t: 'Release notes tab', c: 'hubSub' },
          { t: '· Publish', c: 'hubSub' },
          { t: '· Release Note', c: 'hubSub' },
          { t: '· Product(s) affected', c: 'hubSub' },
          { t: '· Version(s) affected', c: 'hubSub' },
          { t: '+ type, state, severity', c: 'hubSub' },
        ]}
      />

      {lane1.map((b, i) => (
        <Box
          key={b.t}
          x={l1X(i)}
          y={l1Y}
          w={l1W}
          h={bh}
          kind={b.k}
          lines={[
            { t: b.t, c: 'titleSm' },
            { t: b.a, c: 'sub' },
            { t: b.b, c: 'sub' },
          ]}
        />
      ))}
      {lane2.map((b, i) => (
        <Box
          key={b.t}
          x={l2X(i)}
          y={l2Y}
          w={l2W}
          h={bh}
          kind={b.k}
          lines={[
            { t: b.t, c: 'titleSm' },
            { t: b.a, c: 'sub' },
            { t: b.b, c: 'sub' },
          ]}
        />
      ))}

      <Box
        x={865}
        y={80}
        w={125}
        h={210}
        kind="good"
        lh={19}
        lines={[
          { t: 'Customer', c: 'titleSm' },
          { t: 'portal', c: 'titleSm' },
          { t: '' , c: 'sub' },
          { t: 'Release notes', c: 'sub' },
          { t: 'Known issues', c: 'sub' },
          { t: 'Critical + high', c: 'sub' },
          { t: 'bug reports', c: 'sub' },
        ]}
      />

      <Legend
        x={200}
        y={368}
        items={[
          { k: 'human', t: 'human judgment' },
          { k: 'auto', t: 'automated' },
          { k: 'good', t: 'published' },
        ]}
      />
    </Figure>
  );
}

/* =====================================================================
   3. Interactive: one work item, every publication
   ===================================================================== */

const PRODUCTS = ['Data platform', 'Pipeline designer', 'Metadata service'];
const VERSIONS = ['2022.2', '2022.1'];
const SEVERITIES = ['Critical', 'High', 'Medium', 'Low'];
const PUBLISH = ['Yes', 'Yes, but covered elsewhere', 'No', ''];

const PRESETS = {
  feature: {
    label: 'New feature',
    type: 'Feature',
    state: 'Closed',
    severity: 'Medium',
    publish: 'Yes',
    product: 'Data platform',
    version: '2022.2',
    title: 'Descriptions in the data catalog',
    note: 'Entity and binding descriptions are listed on the **Details** pages of the data catalog, so users can understand a data mart without opening its code.',
  },
  fixed: {
    label: 'Fixed bug',
    type: 'Bug',
    state: 'Closed',
    severity: 'Medium',
    publish: 'Yes',
    product: 'Metadata service',
    version: '2022.2',
    title: 'ODBC refresh error',
    note: 'ODBC driver fails when refreshing metadata',
  },
  critical: {
    label: 'Open critical bug',
    type: 'Bug',
    state: 'Active',
    severity: 'Critical',
    publish: 'Yes',
    product: 'Data platform',
    version: '2022.2',
    title: 'Streaming jobs stuck',
    note: 'Streaming jobs erroneously remain in **Processing** state when the processing engine fails to connect to the real-time queue',
  },
  missing: {
    label: 'Forgotten note',
    type: 'Bug',
    state: 'Closed',
    severity: 'Low',
    publish: '',
    product: '',
    version: '2022.2',
    title: 'Subsets cannot be edited',
    note: '',
  },
  duplicate: {
    label: 'Duplicate',
    type: 'Feature',
    state: 'Closed',
    severity: 'Medium',
    publish: 'Yes, but covered elsewhere',
    product: 'Data platform',
    version: '2022.2',
    title: 'Catalog descriptions: API support',
    note: '',
  },
};

// Tiny renderer for **bold** in a release note.
function Rich({ text }) {
  const parts = text.split(/\*\*(.+?)\*\*/g);
  return parts.map((p, i) => (i % 2 ? <strong key={i}>{p}</strong> : <React.Fragment key={i}>{p}</React.Fragment>));
}

function route(w) {
  const bug = w.type === 'Bug';
  const closed = w.state === 'Closed';
  const pub = w.publish === 'Yes';
  const ch = bug && (w.severity === 'Critical' || w.severity === 'High');
  return {
    whatsNew: !bug && closed && pub,
    fixed: bug && closed && pub,
    known: bug && !closed && pub,
    critOpen: bug && !closed && ch,
    critClosed: bug && closed && ch && pub,
    review: closed && !pub,
  };
}

function explain(w, r) {
  const out = [];
  const bug = w.type === 'Bug';
  const closed = w.state === 'Closed';
  if (!bug && !closed) {
    out.push("Open features and backlog items aren't part of a release yet, so nothing publishes. When the item ships, the next release comparison picks it up automatically.");
  }
  if (r.whatsNew) out.push("A closed feature with Publish set to Yes becomes a What's new item. Its heading comes from the work item title.");
  if (r.fixed) out.push('A closed bug with Publish set to Yes becomes a fixed bug in the release notes.');
  if (r.critClosed) out.push("Because it's Critical or High, it's also listed with critical and high bugs closed in the past 60 days.");
  if (r.known) out.push('An open bug with Publish set to Yes is a known issue. It appears on the next daily refresh and disappears on its own when the bug closes.');
  if (r.critOpen) out.push("Because it's open and Critical or High, it's always listed in the open critical and high bugs report. That list doesn't depend on the Publish field.");
  if (bug && !closed && !r.known && !r.critOpen) {
    out.push("An open bug that isn't marked Publish = Yes and isn't Critical or High stays internal.");
  }
  if (r.review) {
    if (w.publish === 'Yes, but covered elsewhere') {
      out.push('Another work item already carries this note, so it stays out of the notes and there are no duplicates. It still appears in the reviewers’ table, so nothing disappears silently.');
    } else {
      out.push("Publish isn't set to Yes, so the note is left out. Because the item shipped in this release, it's listed in a table at the bottom of the pull request, where reviewers can catch a note that should have been included.");
    }
  }
  if (w.publish === 'Yes' && (r.whatsNew || r.fixed || r.known || r.critClosed) && !w.note.trim()) {
    out.push('The Release Note field is empty. The writer catches this during the edit pass.');
  }
  if (w.publish === 'Yes' && !w.product) {
    out.push('No product is selected, so the note has no heading to sort under.');
  }
  return out;
}

export function WorkItemSimulator() {
  const [w, setW] = useState(PRESETS.feature);
  const set = (k) => (e) => setW({ ...w, [k]: e.target.value });
  const r = route(w);
  const why = explain(w, r);
  const bug = w.type === 'Bug';
  const id = 48213;

  const dests = [
    { on: r.whatsNew, t: "Release notes · What's new", s: `${w.product || 'No product'} section` },
    { on: r.fixed, t: 'Release notes · Fixed bugs', s: `${w.product || 'No product'} section` },
    { on: r.known, t: 'Known issues', s: `Version ${w.version} page, refreshed daily` },
    { on: r.critOpen, t: 'Critical + high bugs · Open', s: `Version ${w.version} page, refreshed daily` },
    { on: r.critClosed, t: 'Critical + high bugs · Closed in past 60 days', s: `Version ${w.version} page, refreshed daily` },
    { on: r.review, flag: true, t: 'Reviewers’ table in the pull request', s: 'Shipped but not published: a prompt to double-check' },
  ];

  let preview;
  if (r.whatsNew) {
    preview = (
      <>
        <p className={styles.previewProduct}>{w.product || 'No product'}</p>
        <p className={styles.previewH}>{w.title || 'Untitled'}</p>
        <p className={styles.previewP}>{w.note ? <Rich text={w.note} /> : <em>(empty note)</em>}</p>
      </>
    );
  } else if (r.fixed || r.known || r.critOpen || r.critClosed) {
    preview = (
      <>
        <p className={styles.previewProduct}>{w.product || 'No product'}</p>
        <table className={styles.previewTable}>
          <thead>
            <tr>
              <th>{r.fixed ? 'Fixed bug' : 'Issue'}</th>
              {(r.critOpen || r.critClosed) && <th>Severity</th>}
              <th>ID</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>{w.note ? <Rich text={w.note} /> : <em>(empty note)</em>}</td>
              {(r.critOpen || r.critClosed) && <td>{w.severity}</td>}
              <td>{id}</td>
            </tr>
          </tbody>
        </table>
      </>
    );
  } else if (r.review) {
    preview = (
      <table className={styles.previewTable}>
        <thead>
          <tr>
            <th>Work item title</th>
            <th>Release note</th>
            <th>Products</th>
            <th>ID</th>
            <th>Type</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{w.title || 'Untitled'}</td>
            <td>{w.note ? <Rich text={w.note} /> : ''}</td>
            <td>{w.product}</td>
            <td>{id}</td>
            <td>{w.type}</td>
          </tr>
        </tbody>
      </table>
    );
  } else {
    preview = <p className={styles.previewEmpty}>Nothing publishes from this work item.</p>;
  }

  return (
    <section className={styles.sim} aria-label="Interactive: how a work item's fields decide where it publishes">
      <div className={styles.simBadge}>
        <span>Work item simulator</span>
        <span>Illustrative content · change any field</span>
      </div>

      <div className={styles.presets}>
        <span>Try:</span>
        {Object.entries(PRESETS).map(([k, p]) => (
          <button key={k} type="button" className={styles.presetBtn} onClick={() => setW(p)}>
            {p.label}
          </button>
        ))}
      </div>

      <div className={styles.simBody}>
        {/* ---------- Work item ---------- */}
        <div className={styles.wi}>
          <p className={styles.wiCrumb}>
            {w.type.toUpperCase()} {id}
          </p>
          <input
            className={styles.wiTitle}
            aria-label="Work item title"
            value={w.title}
            onChange={set('title')}
          />

          <div className={styles.wiRow}>
            <label className={styles.field}>
              <span className={styles.label}>Type</span>
              <select value={w.type} onChange={set('type')}>
                <option>Feature</option>
                <option>Product Backlog Item</option>
                <option>Bug</option>
              </select>
            </label>
            <label className={styles.field}>
              <span className={styles.label}>State</span>
              <select value={w.state} onChange={set('state')}>
                <option>Active</option>
                <option>Closed</option>
              </select>
            </label>
            <label className={`${styles.field} ${bug ? '' : styles.fieldOff}`}>
              <span className={styles.label}>Severity</span>
              <select value={w.severity} onChange={set('severity')} disabled={!bug}>
                {SEVERITIES.map((s) => (
                  <option key={s}>{s}</option>
                ))}
              </select>
            </label>
          </div>

          <div className={styles.tabs} aria-hidden="true">
            <span className={styles.tab}>Details</span>
            <span className={styles.tabOn}>RN</span>
            <span className={styles.tab}>History</span>
          </div>

          <label className={styles.field}>
            <span className={styles.label}>Publish</span>
            <select value={w.publish} onChange={set('publish')}>
              {PUBLISH.map((p) => (
                <option key={p || 'unset'} value={p}>
                  {p || '(not set)'}
                </option>
              ))}
            </select>
          </label>

          <div className={styles.wiRow} style={{ gridTemplateColumns: 'repeat(2, minmax(0, 1fr))' }}>
            <label className={styles.field}>
              <span className={styles.label}>Product(s) affected</span>
              <select value={w.product} onChange={set('product')}>
                <option value="">(not set)</option>
                {PRODUCTS.map((p) => (
                  <option key={p}>{p}</option>
                ))}
              </select>
            </label>
            <label className={styles.field}>
              <span className={styles.label}>Version(s) affected</span>
              <select value={w.version} onChange={set('version')}>
                {VERSIONS.map((v) => (
                  <option key={v}>{v}</option>
                ))}
              </select>
            </label>
          </div>

          <label className={styles.field}>
            <span className={styles.label}>Release Note</span>
            <textarea rows={4} value={w.note} onChange={set('note')} />
          </label>
        </div>

        {/* ---------- Where it goes ---------- */}
        <div className={styles.out} aria-live="polite">
          <p className={styles.outHeading}>Where this work item publishes</p>
          <ul className={styles.dests}>
            {dests.map((d) => (
              <li
                key={d.t}
                aria-label={`${d.t}: ${d.on ? `yes. ${d.s}` : 'no'}`}
                className={`${styles.dest} ${d.on ? (d.flag ? styles.destFlag : styles.destOn) : ''}`}>
                <span className={styles.destMark} aria-hidden="true">
                  {d.on ? (d.flag ? '!' : '✓') : '–'}
                </span>
                <span aria-hidden="true">
                  {d.t}
                  {d.on && <span className={styles.destSub}>{d.s}</span>}
                </span>
              </li>
            ))}
          </ul>

          <div className={styles.why}>
            {why.map((s, i) => (
              <p key={i} style={{ margin: i === why.length - 1 ? 0 : '0 0 0.4rem' }}>
                {s}
              </p>
            ))}
          </div>

          <div className={styles.preview}>
            <p className={styles.previewLabel}>Preview</p>
            {preview}
          </div>
        </div>
      </div>
    </section>
  );
}
